version: "3.3"
services:
  server_side:
    container_name: server_side_render
    working_dir: /app
    build:
      context: ./
      dockerfile: ./infra/development/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - ./infra/development/.env
    ports:
      - "3000:3000"